name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  lint:
    name: Code linting and tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
      - name: Lint JS
        run: yarn lint:js
      - name: Lint CSS
        run: yarn lint:styles
      - name: Prettier
        run: yarn prettier -c .
      - name: Validate typescript
        run: yarn tsc -noEmit
      - name: Test
        run: yarn test
